import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { ClerkProvider } from '@clerk/nextjs'

import Topbar from '@/components/shares/Topbar'
import LeftSidebar from '@/components/shares/LeftSidebar'
import RightSidebar from '@/components/shares/RightSidebar'
import Bottombar from '@/components/shares/Bottombar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create Next App',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <Topbar />
        <main>
          <LeftSidebar/>
          <section className="main-container">
            <div className="w-full max-w-4xl">
            {children}
            </div>
          </section>
          <RightSidebar/>
        </main>
        <Bottombar/>
        </body>
    </html>
    </ClerkProvider>
  )
}
